### ISSUE TITLE
Is WorkerID available

### ISSUE THREAD

**Issue by Helenology** [ntucllab/CLImage_Dataset#1]
Hi. Thank you very much for providing these valuable datasets. I wonder if you could provide the WorkerID of the cl_labels. Thank you again!

**Comment by maitanha** [comment]
Hi Helenology,

Thank you for your question.
As mentioned in our paper, we used Amazon mturker to collect human labeling for these datasets.
We have the list of cl_labels' WorkerIDs. Here is a file with the list of WorkerIDs labeled for our CLMIN10 dataset. Please refer to the following file. We will add WorkerIDs of whole datasets in the repository soon.

[github_workerid.csv](https://github.com/user-attachments/files/16797727/github_workerid.csv)

**Comment by maitanha** [comment]
Hi Helenology,

We have added the complete list of worker IDs, who contributed to labeling our CLImage_Dataset, to our repository. You can find the list in the _worker_ids_ folder.
We hope this solved your question.

Thanks!

**Comment by Helenology** [comment]
Thank you very much:)
